name: Auto

on: pull_request_target

jobs:
  approve:
    if: github.actor == 'iamogbz' || github.actor == 'renovate-bot'
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v3.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
