name: Ejection

on:
  push:
    branches:
      - main

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: boilerplate-ejection
        token: ${{ secrets.GH_TOKEN }}
    - run: git config user.name "Project Owner"
    - run: git config user.email "owner@project.com"
    - run: git rebase origin/main
    - run: git push --force --set-upstream origin boilerplate-ejection
