name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0/15 * * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Renovate
        uses: renovatebot/github-action@v32.6.4
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GH_TOKEN }}
